/*
 * MOCK ONLY — delete with the rest of lib/mock when the real server lands.
 *
 * Metadata for the pictograms in public/mock/illustrations (generated by
 * scripts/generate-mock-illustrations.mjs). `tags` say what a picture asserts
 * so the mock check can notice a picture that contradicts its card.
 */
import type { CardRole } from "../domain/document";

export interface LibraryIllustration {
  id: string;
  alt: string;
  meaning: string;
  tags: string[];
  roles: CardRole[];
  keywords: string[];
}

export const ILLUSTRATIONS: LibraryIllustration[] = [
  {
    id: "tenant",
    alt: "사람과 열쇠가 달린 집",
    meaning: "집을 빌려 사는 사람(세입자)",
    tags: ["person", "tenant"],
    roles: ["person"],
    keywords: ["빌려 살", "세입자", "살았던"],
  },
  {
    id: "landlord",
    alt: "열쇠를 가진 사람과 집",
    meaning: "집을 빌려주는 집주인",
    tags: ["person", "landlord"],
    roles: ["person"],
    keywords: ["집주인", "빌려준"],
  },
  {
    id: "court",
    alt: "법원 건물",
    meaning: "재판을 하는 법원",
    tags: ["court"],
    roles: ["background", "finding", "decision"],
    keywords: ["법원", "재판"],
  },
  {
    id: "judge-decides",
    alt: "법봉과 판결문",
    meaning: "법원이 결정을 내리는 모습",
    tags: ["court", "decision"],
    roles: ["decision", "finding"],
    keywords: ["결정", "판결"],
  },
  {
    id: "contract",
    alt: "계약서와 악수하는 손",
    meaning: "집을 빌리기로 약속하는 모습",
    tags: ["contract"],
    roles: ["background"],
    keywords: ["약속", "계약"],
  },
  {
    id: "deposit-paid",
    alt: "한 사람이 다른 사람에게 돈을 건네는 모습",
    meaning: "보증금을 집주인에게 맡기는 모습",
    tags: ["money", "paid", "past"],
    roles: ["background"],
    keywords: ["보증금", "맡기"],
  },
  {
    id: "calendar-end",
    alt: "확인 표시가 있는 달력",
    meaning: "약속한 기간이 끝난 모습",
    tags: ["date", "ended"],
    roles: ["background", "finding"],
    keywords: ["기간", "끝나"],
  },
  {
    id: "moving-out",
    alt: "집에서 나오는 사람",
    meaning: "집을 비워 주고 나가는 모습",
    tags: ["move-out", "past"],
    roles: ["background"],
    keywords: ["비워", "나가"],
  },
  {
    id: "money-not-returned",
    alt: "X 표시가 있는 돈",
    meaning: "돈을 돌려주지 않은 모습",
    tags: ["money", "not-returned"],
    roles: ["background", "claim"],
    keywords: ["돌려주지 않", "줄 수 없"],
  },
  {
    id: "asking-money-back",
    alt: "사람과 돈이 그려진 말풍선",
    meaning: "돈을 돌려 달라고 요청하는 모습",
    tags: ["claim", "money", "request"],
    roles: ["claim"],
    keywords: ["달라고", "돌려 달라"],
  },
  {
    id: "refusing",
    alt: "사람과 X 표시가 있는 말풍선",
    meaning: "돈을 돌려줄 수 없다고 말하는 모습",
    tags: ["claim", "refuse"],
    roles: ["claim"],
    keywords: ["없다고", "못 구해"],
  },
  {
    id: "wallpaper-damage",
    alt: "경고 표시가 있는 벽과 붓",
    meaning: "벽지가 망가진 모습",
    tags: ["damage", "wallpaper"],
    roles: ["claim", "finding", "background"],
    keywords: ["벽지", "망가"],
  },
  {
    id: "floor-unknown",
    alt: "소파와 물음표가 있는 돋보기",
    meaning: "바닥이 망가졌는지 확실하지 않은 모습",
    tags: ["evidence-lacking", "floor"],
    roles: ["finding", "claim"],
    keywords: ["바닥", "증거"],
  },
  {
    id: "weighing",
    alt: "저울 양쪽에 있는 두 사람",
    meaning: "법원이 양쪽 이야기를 따져 보는 모습",
    tags: ["court", "weighing"],
    roles: ["finding"],
    keywords: ["봤어요", "판단", "따져"],
  },
  {
    id: "court-orders-payment",
    alt: "법봉에서 돈을 거쳐 사람에게 가는 화살표",
    meaning: "법원이 돈을 돌려주라고 결정하는 모습(아직 주지 않음)",
    tags: ["court", "money", "order-to-pay", "future"],
    roles: ["decision"],
    keywords: ["돌려줘야", "주라고", "줘야"],
  },
  {
    id: "money-received",
    alt: "확인 표시가 있는 사람과 돈",
    meaning: "이미 돈을 받은 모습",
    tags: ["money", "received", "past"],
    roles: ["background"],
    keywords: ["받았", "받은"],
  },
  {
    id: "interest-added",
    alt: "더하기 표시가 있는 돈과 시계",
    meaning: "늦게 준 만큼 돈이 더 붙는 모습",
    tags: ["money", "interest"],
    roles: ["decision"],
    keywords: ["이자", "늦게"],
  },
  {
    id: "cost-split",
    alt: "동전 더미 양쪽에 있는 두 사람",
    meaning: "재판 비용을 나누어 내는 모습",
    tags: ["money", "costs"],
    roles: ["decision"],
    keywords: ["비용", "나누", "내요"],
  },
  {
    id: "deduct-repair",
    alt: "빼기 표시가 있는 돈과 붓",
    meaning: "고치는 비용을 빼는 모습",
    tags: ["money", "deduct"],
    roles: ["finding", "decision"],
    keywords: ["빼", "고치"],
  },
  {
    id: "new-tenant-search",
    alt: "돋보기로 사람을 찾는 모습과 집",
    meaning: "새로 들어올 사람을 찾는 모습",
    tags: ["search", "tenant"],
    roles: ["claim", "finding"],
    keywords: ["새로 들어올", "구해"],
  },
  {
    id: "evidence-photo",
    alt: "카메라와 서류",
    meaning: "증거로 낸 사진과 서류",
    tags: ["evidence"],
    roles: ["finding"],
    keywords: ["증거", "사진"],
  },
  {
    id: "not-accepted",
    alt: "X 표시가 있는 말풍선과 저울",
    meaning: "법원이 주장을 받아들이지 않는 모습",
    tags: ["court", "rejected"],
    roles: ["finding", "decision"],
    keywords: ["받아들이지 않", "이유가 되지 않"],
  },
];

export function illustrationSrc(id: string) {
  return `/mock/illustrations/${id}.svg`;
}

export function findIllustration(id: string) {
  return ILLUSTRATIONS.find((illustration) => illustration.id === id);
}

/** Maps a document image back to the library entry it came from, if any. */
export function illustrationForSrc(src: string) {
  const match = /\/mock\/illustrations\/([\w-]+)\.svg$/.exec(src);
  return match ? findIllustration(match[1]) : undefined;
}
